"""init

Revision ID: e1f78736b2bc
Revises:

"""
import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "e1f78736b2bc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("product_code", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
    )
    op.create_index(op.f("ix_products_product_code"), "products", ["product_code"], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_product_code"), table_name="products")
    op.drop_table("products")
    ### end Alembic commands ###
